model_type: high_order_conv
layer_type: "continuous1d"
n: 2
periodicity: 2.0
kernel_size: [10, 10, 10, 10]
stride: [10, 10, 10, 10]
channels: [1, 2, 4, 16]
segments: 2
normalize: true
out_features: 1
