layer_type: "continuous1d"
normalize: true
rescale_output: False

# Number of characters as input. Convnet can
# have a much larger context
features: ${data.window_size}
out_features: 1

model_type: high_order_tail_focus

n: 2
periodicity: 2.0
kernel_size: [10, 10, 10]
stride: [10, 10, 10]
channels: [1, 32, 32]
segments: 4 #[2, 20, 20, 20, 20]

# Focus [0,16] 16 would take 16*channels
focus: [128, 64] # focus takes all of the final output
