filename: music/TeaKPea-vpunk.mp3
n: 3
conv:
  layer_type: "continuous1d"
  n: ${n}
  periodicity: 2.0
  kernel_size: [10, 10, 10, 10]
  stride: [10, 10, 10, 10]
  channels: [1, 2, 4, 16]
  segments: 2

mlp:
  layer_type: "polynomial"
  n: ${n}
  n_in: null
  n_out: null
  n_hidden: null
  periodicity: null
  rescale_output: False
  scale: 2.0
  input:
    segments: 1
    width: 2
  output:
    segments: 1
    width: 3
  hidden:
    segments: 1
    layers: 2
    width: 10
data:
  window_size: 10000
  output_window_size: 1

max_epochs: 50
gpus: 1
lr: 1e-3
batch_size: 512

# Are you training? Otherwise plot the result
train: True
checkpoint: null
rotations: 1 # 1 is x,y, 2 is x,y, x-y, x+y, greater includes additional rotations

defaults:
  - optimizer: adam
